<?php

declare(strict_types=1);
namespace App\Services;
use App\Database;
use RuntimeException;
final class OrderWalletService
{
    public static function reserve(int $orderId,int $userId,float $amount):void
    {
        $pdo=Database::connection();$pdo->beginTransaction();
        try{$stmt=$pdo->prepare('SELECT balance FROM users WHERE id=:id FOR UPDATE');$stmt->execute([':id'=>$userId]);$balance=$stmt->fetchColumn();if($balance===false)throw new RuntimeException('User not found.');$amount=round($amount,4);if((float)$balance<$amount)throw new RuntimeException('Insufficient wallet balance.');$ref='ORDER-RESERVE-'.$orderId;$exists=$pdo->prepare('SELECT id FROM order_wallet_reservations WHERE order_id=:order_id LIMIT 1');$exists->execute([':order_id'=>$orderId]);if($exists->fetchColumn()!==false){$pdo->rollBack();return;}$after=(float)$balance-$amount;$pdo->prepare('UPDATE users SET balance=:balance WHERE id=:id')->execute([':balance'=>$after,':id'=>$userId]);$pdo->prepare("INSERT INTO transactions(user_id,type,amount,balance_before,balance_after,reference,description,status) VALUES(:uid,'order',:amount,:before,:after,:ref,:description,'completed')")->execute([':uid'=>$userId,':amount'=>-$amount,':before'=>$balance,':after'=>$after,':ref'=>$ref,':description'=>'Reserved for order #'.$orderId]);$tx=(int)$pdo->lastInsertId();$pdo->prepare('INSERT INTO wallet_ledger(user_id,transaction_id,direction,amount,balance_before,balance_after,reference,metadata) VALUES(:uid,:tx,\'debit\',:amount,:before,:after,:ref,:metadata)')->execute([':uid'=>$userId,':tx'=>$tx,':amount'=>$amount,':before'=>$balance,':after'=>$after,':ref'=>$ref,':metadata'=>json_encode(['order_id'=>$orderId,'type'=>'order_reservation'],JSON_THROW_ON_ERROR)]);$pdo->prepare('INSERT INTO order_wallet_reservations(order_id,user_id,amount,status,reserve_reference) VALUES(:order_id,:user_id,:amount,\'reserved\',:ref)')->execute([':order_id'=>$orderId,':user_id'=>$userId,':amount'=>$amount,':ref'=>$ref]);$pdo->commit();}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
    }
    public static function release(int $orderId,string $reason):void
    {
        $pdo=Database::connection();$pdo->beginTransaction();
        try{$stmt=$pdo->prepare('SELECT * FROM order_wallet_reservations WHERE order_id=:id FOR UPDATE');$stmt->execute([':id'=>$orderId]);$r=$stmt->fetch();if(!$r||$r['status']==='released'){$pdo->rollBack();return;}if($r['status']!=='reserved')throw new RuntimeException('Reservation cannot be released.');$u=$pdo->prepare('SELECT balance FROM users WHERE id=:id FOR UPDATE');$u->execute([':id'=>$r['user_id']]);$before=(float)$u->fetchColumn();$after=$before+(float)$r['amount'];$ref='ORDER-RELEASE-'.$orderId;$pdo->prepare('UPDATE users SET balance=:balance WHERE id=:id')->execute([':balance'=>$after,':id'=>$r['user_id']]);$pdo->prepare("INSERT INTO transactions(user_id,type,amount,balance_before,balance_after,reference,description,status) VALUES(:uid,'refund',:amount,:before,:after,:ref,:description,'completed')")->execute([':uid'=>$r['user_id'],':amount'=>$r['amount'],':before'=>$before,':after'=>$after,':ref'=>$ref,':description'=>'Released order reservation #'.$orderId.': '.mb_substr($reason,0,180)]);$tx=(int)$pdo->lastInsertId();$pdo->prepare('INSERT INTO wallet_ledger(user_id,transaction_id,direction,amount,balance_before,balance_after,reference,metadata) VALUES(:uid,:tx,\'credit\',:amount,:before,:after,:ref,:metadata)')->execute([':uid'=>$r['user_id'],':tx'=>$tx,':amount'=>$r['amount'],':before'=>$before,':after'=>$after,':ref'=>$ref,':metadata'=>json_encode(['order_id'=>$orderId,'type'=>'order_reservation_release','reason'=>$reason],JSON_THROW_ON_ERROR)]);$pdo->prepare("UPDATE order_wallet_reservations SET status='released',release_reference=:ref,released_at=NOW() WHERE id=:id")->execute([':ref'=>$ref,':id'=>$r['id']]);$pdo->commit();}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
    }
}
