<?php

declare(strict_types=1);
require dirname(__DIR__) . '/config/bootstrap.php';
use App\Auth; use App\Database;
Auth::requireLogin();
$stmt=Database::connection()->query("SELECT s.id,s.name,s.provider_type,s.selling_rate,s.min_quantity,s.max_quantity,s.refill,s.cancel,c.name category FROM services s LEFT JOIN categories c ON c.id=s.category_id WHERE s.status=1 ORDER BY COALESCE(c.sort_order,0),c.name,s.id");
$services=$stmt->fetchAll();
$grouped=[]; foreach($services as $service){$grouped[$service['category']??'Uncategorized'][]=$service;}
$currency=(string)env('CURRENCY','NGN');
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Services | SMM Panel</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"></head><body class="bg-light"><nav class="navbar navbar-dark bg-dark"><div class="container"><a class="navbar-brand" href="/dashboard.php">SMM Panel</a><a class="btn btn-outline-light btn-sm" href="/orders.php">My Orders</a></div></nav><main class="container py-4"><div class="d-flex justify-content-between align-items-center mb-4"><div><h2 class="mb-1">Services</h2><div class="text-muted">Choose a service and place your order.</div></div><a class="btn btn-primary" href="/order.php">New Order</a></div><?php if(!$grouped):?><div class="alert alert-info">No services are currently available. Please check back shortly.</div><?php endif;?><?php foreach($grouped as $category=>$items):?><section class="mb-4"><h4 class="mb-3"><?=htmlspecialchars($category)?></h4><div class="table-responsive"><table class="table table-hover bg-white align-middle shadow-sm"><thead><tr><th>Service</th><th>Type</th><th>Rate / 1K</th><th>Limits</th><th>Features</th><th></th></tr></thead><tbody><?php foreach($items as $s):?><tr><td><strong><?=htmlspecialchars($s['name'])?></strong></td><td><?=htmlspecialchars($s['provider_type'])?></td><td><?=htmlspecialchars($currency)?> <?=number_format((float)$s['selling_rate'],4)?></td><td><?= (int)$s['min_quantity']?>–<?= (int)$s['max_quantity']?></td><td><?php if((int)$s['refill']===1):?><span class="badge text-bg-success me-1">Refill</span><?php endif;?><?php if((int)$s['cancel']===1):?><span class="badge text-bg-warning">Cancel</span><?php endif;?></td><td><a class="btn btn-sm btn-outline-primary" href="/order.php?service=<?= (int)$s['id'] ?>">Order</a></td></tr><?php endforeach;?></tbody></table></div></section><?php endforeach;?></main></body></html>
