<?php

declare(strict_types=1);
require dirname(__DIR__,2).'/config/bootstrap.php';
use App\Database;use App\Services\AdminService;
AdminService::requireAdmin();$pdo=Database::connection();
$jobs=$pdo->query('SELECT * FROM job_runs ORDER BY started_at DESC LIMIT 30')->fetchAll();
$failed=(int)$pdo->query("SELECT COUNT(*) FROM job_runs WHERE status='failed' AND started_at >= NOW()-INTERVAL 24 HOUR")->fetchColumn();
$orders=(int)$pdo->query("SELECT COUNT(*) FROM orders WHERE status NOT IN ('completed','cancelled','canceled','failed')")->fetchColumn();
$refunds=(float)$pdo->query("SELECT COALESCE(SUM(amount),0) FROM refund_events WHERE status='completed' AND created_at >= NOW()-INTERVAL 24 HOUR")->fetchColumn();
$profit=(float)$pdo->query("SELECT COALESCE(SUM(profit),0) FROM orders WHERE created_at >= NOW()-INTERVAL 24 HOUR")->fetchColumn();
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Operations | SMM Admin</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"></head><body class="bg-light"><nav class="navbar navbar-dark bg-dark"><div class="container-fluid"><a class="navbar-brand" href="/admin/">SMM Operations</a></div></nav><main class="container-fluid py-4"><h2>Production Operations</h2><div class="row g-3 mb-4"><div class="col-md-3"><div class="card"><div class="card-body"><small class="text-muted">Failed jobs / 24h</small><h3><?=number_format($failed)?></h3></div></div></div><div class="col-md-3"><div class="card"><div class="card-body"><small class="text-muted">Active orders</small><h3><?=number_format($orders)?></h3></div></div></div><div class="col-md-3"><div class="card"><div class="card-body"><small class="text-muted">Refunds / 24h</small><h3>₦<?=number_format($refunds,2)?></h3></div></div></div><div class="col-md-3"><div class="card"><div class="card-body"><small class="text-muted">Order profit / 24h</small><h3>₦<?=number_format($profit,2)?></h3></div></div></div></div><div class="card"><div class="card-header">Recent jobs</div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Job</th><th>Status</th><th>Processed</th><th>Updated</th><th>Failed</th><th>Started</th><th>Finished</th><th>Error</th></tr></thead><tbody><?php foreach($jobs as $j):?><tr><td><?=htmlspecialchars($j['job_name'])?></td><td><span class="badge text-bg-<?= $j['status']==='completed'?'success':($j['status']==='failed'?'danger':'warning')?>"><?=htmlspecialchars($j['status'])?></span></td><td><?=number_format((int)$j['processed'])?></td><td><?=number_format((int)$j['updated'])?></td><td><?=number_format((int)$j['failed'])?></td><td><?=htmlspecialchars($j['started_at'])?></td><td><?=htmlspecialchars((string)($j['finished_at']??'-'))?></td><td class="text-danger small"><?=htmlspecialchars((string)($j['error_message']??''))?></td></tr><?php endforeach;?></tbody></table></div></div></main></body></html>
