<?php

declare(strict_types=1);
require dirname(__DIR__,2).'/config/bootstrap.php';
use App\Database; use App\Auth; use App\Services\AdminService;
AdminService::requireAdmin();
$orders=Database::connection()->query('SELECT o.id,o.status,o.quantity,o.charge,o.provider_order_id,o.profit,o.refill_id,o.created_at,u.email,s.name service,s.refill,s.cancel FROM orders o JOIN users u ON u.id=o.user_id JOIN services s ON s.id=o.service_id ORDER BY o.id DESC LIMIT 200')->fetchAll();
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Orders | Admin</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"></head><body class="bg-light"><nav class="navbar navbar-dark bg-dark"><div class="container-fluid"><a class="navbar-brand" href="/admin/">SMM Admin</a></div></nav><main class="container-fluid py-4"><h2>Orders</h2><div class="table-responsive"><table class="table bg-white align-middle"><thead><tr><th>#</th><th>Customer</th><th>Service</th><th>Provider ID</th><th>Qty</th><th>Charge</th><th>Profit</th><th>Status</th><th>Actions</th></tr></thead><tbody><?php foreach($orders as $o):?><tr><td><?= (int)$o['id']?></td><td><?=htmlspecialchars($o['email'])?></td><td><?=htmlspecialchars($o['service'])?></td><td><?=htmlspecialchars((string)($o['provider_order_id']??'-'))?></td><td><?=number_format((int)$o['quantity'])?></td><td>₦<?=number_format((float)$o['charge'],2)?></td><td>₦<?=number_format((float)$o['profit'],2)?></td><td><?=htmlspecialchars($o['status'])?></td><td><div class="d-flex gap-1"><?php if((int)$o['cancel']===1 && !in_array(strtolower($o['status']),['completed','cancelled','canceled','failed'],true)):?><form method="post" action="/admin/order-actions.php"><input type="hidden" name="_csrf" value="<?=htmlspecialchars(Auth::csrfToken())?>"><input type="hidden" name="order_id" value="<?= (int)$o['id']?>"><input type="hidden" name="action" value="cancel"><button class="btn btn-sm btn-outline-danger" onclick="return confirm('Cancel this order?')">Cancel</button></form><?php endif;?><?php if((int)$o['refill']===1 && in_array(strtolower($o['status']),['completed','partial'],true) && empty($o['refill_id'])):?><form method="post" action="/admin/order-actions.php"><input type="hidden" name="_csrf" value="<?=htmlspecialchars(Auth::csrfToken())?>"><input type="hidden" name="order_id" value="<?= (int)$o['id']?>"><input type="hidden" name="action" value="refill"><button class="btn btn-sm btn-outline-primary">Refill</button></form><?php endif;?></div></td></tr><?php endforeach;?></tbody></table></div></main></body></html>
