<?php

declare(strict_types=1);
require dirname(__DIR__,2).'/config/bootstrap.php';
use App\Auth; use App\Database; use App\Services\AdminService;
AdminService::requireAdmin(); $pdo=Database::connection(); $message=null; $error=null;
if($_SERVER['REQUEST_METHOD']==='POST'){
 Auth::verifyCsrf($_POST['_csrf']??null); $id=(int)$_POST['id']; $rate=(float)$_POST['selling_rate']; $markup=($_POST['markup_percent']??'')===''?null:(float)$_POST['markup_percent'];
 try{AdminService::updateServicePricing($id,$rate,$markup);$message='Pricing updated.';}catch(Throwable $e){$error=$e->getMessage();}
}
$services=$pdo->query('SELECT s.*,c.name category FROM services s LEFT JOIN categories c ON c.id=s.category_id ORDER BY c.name,s.id')->fetchAll();
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Services | Admin</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"></head><body class="bg-light"><nav class="navbar navbar-dark bg-dark"><div class="container-fluid"><a class="navbar-brand" href="/admin/">SMM Admin</a></div></nav><main class="container-fluid py-4"><h2>Service Pricing</h2><?php if($message):?><div class="alert alert-success"><?=htmlspecialchars($message)?></div><?php endif;?><?php if($error):?><div class="alert alert-danger"><?=htmlspecialchars($error)?></div><?php endif;?><div class="table-responsive"><table class="table bg-white align-middle"><thead><tr><th>ID</th><th>Category</th><th>Service</th><th>Provider Rate</th><th>Selling Rate / 1K</th><th>Markup %</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($services as $s):?><tr><form method="post"><input type="hidden" name="_csrf" value="<?=htmlspecialchars(Auth::csrfToken())?>"><input type="hidden" name="id" value="<?= (int)$s['id']?>"><td><?= (int)$s['id']?></td><td><?=htmlspecialchars($s['category']??'')?></td><td><?=htmlspecialchars($s['name'])?></td><td><?=number_format((float)$s['provider_rate'],6)?></td><td><input class="form-control form-control-sm" style="max-width:150px" name="selling_rate" type="number" step="0.000001" min="0" value="<?=htmlspecialchars((string)$s['selling_rate'])?>"></td><td><input class="form-control form-control-sm" style="max-width:100px" name="markup_percent" type="number" step="0.01" min="0" value="<?=htmlspecialchars((string)($s['markup_percent']??''))?>"></td><td><?=((int)$s['status']===1)?'Active':'Disabled'?></td><td><button class="btn btn-sm btn-primary">Save</button></td></form></tr><?php endforeach;?></tbody></table></div></main></body></html>
